From registry.access.redhat.com/ubi8/ubi:8.1

WORKDIR /root

#update image and isntall python3/bomber
RUN yum -y update && yum install -y python3

#install epel repo
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

#run the download script
ENTRYPOINT ["python3", "./rpm_download.py"]
