From registry.access.redhat.com/ubi9-init 

WORKDIR /root

#update image and install python3/bomber
RUN yum -y update && yum install -y python3

#install epel repository

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

#run the download script
ENTRYPOINT ["python3", "./rpm_download.py"]
